name = "line-crm-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true
account_id = "229bf2a0291a81cfe581a1f9bbb24432"

# API_KEY is set via `wrangler secret put API_KEY`
# Do NOT hardcode secrets here

[vars]
WORKER_URL = "https://line-crm-worker.line-crm-api.workers.dev"
ALLOWED_ORIGINS = "*"
DISCORD_APP_PUBLIC_KEY = "e66f66f0bdb79e8b7d603e6a76a523e2f82561d761490f274160ae04f34a4c68"
DISCORD_CHANNEL_ID = "1488528552860323941"

[[d1_databases]]
binding = "DB"
database_name = "line-crm"
database_id = "e626281f-33ee-4128-a583-6bd367ba8340"

[triggers]
crons = ["*/5 * * * *"]
