#!/bin/bash
set -euo pipefail

echo "=== Google Calendar連携セットアップ ==="
echo ""
echo "以下の手順でGoogle Calendar APIを設定してください。"
echo ""
echo "1. Google Cloud Console (https://console.cloud.google.com) でプロジェクト作成"
echo "   - 既存プロジェクトがあればそれを使用してもOK"
echo ""
echo "2. Calendar API を有効化"
echo "   - APIs & Services > Enable APIs > Google Calendar API"
echo "   - または: gcloud services enable calendar-json.googleapis.com"
echo ""
echo "3. サービスアカウント作成"
echo "   - IAM & Admin > Service Accounts > Create Service Account"
echo "   - ロール: 不要（カレンダーは共有設定で権限付与）"
echo "   - または:"
echo "     gcloud iam service-accounts create line-harness-calendar \\"
echo "       --display-name=\"LINE Harness Calendar\""
echo ""
echo "4. JSONキーをダウンロード"
echo "   - Service Account > Keys > Add Key > Create new key > JSON"
echo "   - または:"
echo "     gcloud iam service-accounts keys create key.json \\"
echo "       --iam-account=line-harness-calendar@PROJECT_ID.iam.gserviceaccount.com"
echo ""
echo "5. JSONキーからWorker secretsに設定:"
echo ""
echo "   # メールアドレス (client_email)"
echo "   wrangler secret put GOOGLE_SERVICE_ACCOUNT_EMAIL"
echo ""
echo "   # 秘密鍵 (private_key) - \\n含む全文を貼り付け"
echo "   wrangler secret put GOOGLE_SERVICE_ACCOUNT_KEY"
echo ""
echo "   # カレンダーID (通常はGmailアドレス)"
echo "   wrangler secret put GOOGLE_CALENDAR_ID"
echo ""
echo "6. Googleカレンダーの共有設定"
echo "   - Googleカレンダー > 設定 > 特定のユーザーとの共有"
echo "   - サービスアカウントのメールアドレスを追加"
echo "   - 権限: 「変更および共有の管理権限」"
echo ""
echo "=== コスト情報 ==="
echo "Google Calendar API: 無料（100万リクエスト/日）"
echo "出典: https://developers.google.com/calendar/api/guides/quota"
echo ""
echo "=== 設定確認 ==="
echo "設定後、以下のコマンドでテスト:"
echo "  curl -H 'Authorization: Bearer YOUR_API_KEY' \\"
echo "    'https://YOUR_WORKER.workers.dev/api/bookings/available?date=2026-03-28'"
